name: Publish NuGet package

on:
  push:
    tags:
      - '*'

jobs:
  build-and-publish:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Setup .NET Core
        uses: actions/setup-dotnet@v3
        with:
          dotnet-version: 7

      - name: Extract version from tag
        id: extract_version
        run: echo "::set-output name=version::${GITHUB_REF#refs/tags/v}"

      - name: Build and publish
        env:
          NUGET_API_KEY: ${{ secrets.NUGET_API_KEY }}
          PACKAGE_VERSION: ${{ steps.extract_version.outputs.version }}
        run: |
          cd src/SwaggerEnrichers
          dotnet build --configuration Release
          dotnet pack --configuration Release --output ./artifacts -p:PackageVersion=${{ env.PACKAGE_VERSION }}
          dotnet nuget push ./artifacts/*.nupkg --api-key ${{ env.NUGET_API_KEY }} --source https://api.nuget.org/v3/index.json